# Generated by Django 3.2.4 on 2021-06-29 12:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('blogitems', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.bloglist')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
    ]
