# Generated by Django 3.2.4 on 2021-06-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglist',
            old_name='about',
            new_name='intro',
        ),
    ]
