# Generated by Django 3.2.4 on 2021-06-29 13:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_about_bloglist_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglist',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
