# Generated by Django 3.2.4 on 2021-06-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bloglist_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogDetail',
        ),
    ]
