# Generated by Django 3.2.4 on 2021-06-30 07:56

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_blogdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=30)),
                ('blogitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloglist')),
            ],
        ),
    ]
