# Generated by Django 3.2.4 on 2021-06-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_bloglist_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'verbose_name': 'post', 'verbose_name_plural': 'post'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
