# Generated by Django 3.2.4 on 2021-06-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210630_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
