# Generated by Django 3.2.4 on 2021-06-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_response_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='blogitem',
            new_name='post',
        ),
    ]
