# Generated by Django 3.2.4 on 2021-06-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_blogitem_response_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='blog.post'),
        ),
    ]
