# Generated by Django 3.2.4 on 2021-06-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_one_banner_three_banner_two'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner_one',
            options={'managed': True, 'verbose_name': 'banner_one', 'verbose_name_plural': 'banner_one'},
        ),
        migrations.AlterModelOptions(
            name='banner_three',
            options={'managed': True, 'verbose_name': 'banner_three', 'verbose_name_plural': 'banner_three'},
        ),
        migrations.AlterModelOptions(
            name='banner_two',
            options={'managed': True, 'verbose_name': 'banner_two', 'verbose_name_plural': 'banner_two'},
        ),
        migrations.AlterModelTable(
            name='banner_one',
            table='banner_one',
        ),
        migrations.AlterModelTable(
            name='banner_three',
            table='banner_three',
        ),
        migrations.AlterModelTable(
            name='banner_two',
            table='banner_two',
        ),
    ]
