# Generated by Django 3.2.4 on 2021-06-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210622_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
