# Generated by Django 3.2.4 on 2021-06-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_updateme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateme',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
