# Generated by Django 3.2.4 on 2021-06-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_updateme_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='default_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
