# Generated by Django 3.2.4 on 2021-07-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_setting_default_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner_one',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='banner_one',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='banner_one',
            name='image3',
        ),
    ]
