# Generated by Django 3.2.4 on 2021-06-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210627_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='size',
        ),
    ]
