# Generated by Django 3.2.4 on 2021-06-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210628_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
