# Generated by Django 3.2.4 on 2021-07-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_mobile_phone_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='home_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
