# Generated by Django 3.2.4 on 2021-07-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210720_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prodname',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
