# Generated by Django 3.2.4 on 2021-06-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avialbility',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Screen_size',
            new_name='screen_size',
        ),
    ]
