# Generated by Django 3.2.4 on 2021-06-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210623_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
