# Generated by Django 3.2.4 on 2021-06-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='HDD',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='RAM',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
